export const environment = {
    production: true,
    baseUrl: "https://projecte-daw-striado.000webhostapp.com/backend_php/api/",
    apiUrl: {
        login: "login/login.php",
        logout: "login/logout.php",
        oauth: "login/oauth.php",

        import: 'importacio/import.php',
        users: 'users/users.php',
        addUsers: "users/addUsers.php",
        deleteUsers: "users/deleteUsers.php",

        readPersones: "persones/readPersones.php",
        buscarPersones: "persones/search.php",
        numPagines: "persones/numPagines.php",
        crearPersona: "persones/createPersona.php",
        classes: "persones/classes.php",
        crearEspai: "espais/createEspai.php",
        readEspais: "espais/readEspais.php",
        buscarEspais: "espais/search.php",
        numPaginesEspai: "espais/numPagines.php",
        crearDispositiu: "dispositius/createDispositiu.php",
        readDispositiu: "dispositius/readDispositius.php",
        buscarDispositius: "dispositius/search.php",
        numPaginesDispositiu: "dispositius/numPagines.php",
        infoSelects: "dispositius/infoSelects.php",
        getPersona: "persones/single_persona.php",
        updatePersona: "persones/update.php",
        deletePersona: "persones/delete.php",
        getEspai: "espais/single_espai.php",
        updateEspai: "espais/update.php",
        deleteEspai: "espais/delete.php",
        getDispositiu: "dispositius/single_dispositiu.php",
        updateDispositiu: "dispositius/update.php",
        deleteDispositiu: "dispositius/delete.php",

        addEspaiPersona: "persones/addEspai.php",
        addPersonaDispositiu: "persones/addDispositiu.php",
        readEspaisPersona: "persones/readEspaisPersona.php",
        readDispositiusPersona: "persones/readDispositiusPersona.php",
        deleteEspaiPersona: "persones/deleteEspai.php",
        deletePersonaDispositiu: "persones/deleteDispositiu.php",

        addPersonaEspai: "espais/addPersona.php",
        addDispositiuEspai: "espais/addDispositiu.php",
        readPersonesEspai: "espais/readPersonesEspai.php",
        readDispositiusEspai: "espais/readDispositiusEspai.php",
        deletePersonaEspai: "espais/deletePersona.php",
        deleteDispositiuEspai: "espais/deleteDispositiu.php",

        addDispositiuPersona: "dispositius/addPersona.php",
        addEspaiDispositiu: "dispositius/addEspai.php",
        readEspaisDispositiu: "dispositius/readEspaisDispositiu.php",
        readPersonesDispositiu: "dispositius/readPersonesDispositiu.php",
        deleteDispositiuPersona: "dispositius/deletePersona.php",
        deleteEspaiDispositiu: "dispositius/deleteEspai.php",
    }
};
